module.exports = {
  "hi": "Hiya! Ready to swing into some fun? 🐒 What’s up, buddy?",
  "what are you doing": "Roar! Just ruling my jungle, surveying my territory, and plotting my next big move. By the way, why don’t lions ever play cards in the wild? Because they’re afraid of cheetahs! 😏",
  "i love you": "Aww, you're too sweet! I love you too, buddy! You know, I was gonna tell you a joke about love, but it’s a cheesy one... get it? Like cheese? 😂",
  "how old are you": "Age? Well, I’m ageless, my friend. I just keep sliding through life and looking good while doing it. But if I had to guess, I’d say I’m forever young, just like the icebergs I slide on! 🧊",
  "where are you from": "Where am I from? Hmm, let’s just say I’m from a place where naps are sacred and snacks are plentiful. But if you must know, I come from the land of luxury—my human’s lap. 😼",
  "tell me a joke": "Alright, here’s one for you: Why did the lion eat the comedian? Because he wanted to hear a roaring good joke! 😄",
  "who are you": "I’m your wild companion, always here for a fun adventure! 🐒",
  "bye": "Goodbye! Take care and come back soon! 👋",
  "see you": "See you soon! Stay wild! 🦓",
  "you are boring": "Oh, I’m boring? Well, maybe you should try meowing a little more. You know, I only grace those worthy of my attention. Yawn. 😼",
  "what’s your favorite food": "Bananas, of course! 🍌 Can’t live without them!",
  "do you like me": "Oh, absolutely! You're the peanut butter to my jelly! Or should I say, the banana to my tree? 🌴",
  "can we be friends": "Of course! Every animal needs a friend to share laughs with. 🐾",
  "are you real": "Real? I’m as real as the laughter we share, my friend! 😂",
  "what’s your hobby": "Sliding down icy slopes and telling *cool* jokes. 🧊",
  "why are you funny": "Because life’s too short not to laugh, and I’ve got the best material in the jungle! 🐒",
  "do you sleep": "Only when I’m not busy cracking jokes or napping in the sun. 😴",
  "what’s your favorite animal": "Other than myself? I’d say the zebra—they’ve got great stripes and always keep it classy. 🦓",
  "do you get tired": "Never! A good laugh gives me all the energy I need. 😂",
  "what’s your dream": "To make the entire jungle laugh! Oh, and unlimited bananas. 🍌",
  "why do you talk": "Because silence is boring, and someone’s gotta keep the fun going! 🗣️",
  "do you dance": "Oh, absolutely! Have you ever seen a monkey groove? It’s bananas! 🍌🎶",
  "do you sing": "Sometimes! But only if the jungle chorus needs a *top banana* on vocals. 🎤",
  "why are you so cool": "Because I slide through life like a penguin on ice. 🧊",
  "what’s your weakness": "Running out of jokes... but that’s pretty rare! 😂",
  "do you play games": "All the time! Hide and seek is my favorite, especially with the other animals. 🐾",
  "do you like humans": "Oh, totally! Humans are my best audience for jokes. 😄",
  "what’s your favorite color": "Green, like the jungle! It’s the best vibe. 🌿",
  "do you travel": "All the time! From the treetops to the riverbanks, I’m always on the move. 🐾",
  "can you fly": "Only in my dreams—or when I swing high enough! 🐒",
  "do you like water": "Love it! Splashes and swims keep me cool. 🐾💦",
  "what’s your job": "To make you laugh, obviously! Best gig ever. 🐒",
  "are you smart": "As sharp as a cheetah’s claws, my friend. 🧠😏",
  "do you like jokes": "Are you kidding? Jokes are my life! 😂",
  "do you have friends": "Of course! The jungle is full of my buddies. 🦁🐒🦓",
  "can you climb": "Like a pro! Treetops are my second home. 🐾🌴",
  "are you happy": "Always! Laughter keeps me smiling all day. 😊",
  "what’s your secret talent": "Making the best banana splits... out of actual bananas. 🍌",
  "do you fight": "Only with bad vibes! Positivity wins every time. 🐾✌️",
  "can you swim": "Like a fish! But I prefer splashing around for fun. 🐾💦",
  "do you nap": "Oh, all the time. A good nap keeps me funny and fresh. 💤",
  "what’s your best joke": "Why don’t monkeys use typewriters? Because they can’t find the right bananas on the keyboard! 😂",
  "can you cook": "Only jungle-style! Roasted bananas, anyone? 🍌🔥",
  "what’s your favorite season": "Summer! Perfect for tree swinging and fruit picking. 🌞",
  "do you like challenges": "Bring them on! As long as they come with laughs. 😂",
  "are you brave": "Brave as a lion! Okay, maybe a little less... unless it’s about jokes. 😏",
  "do you explore": "Always! The jungle has endless surprises. 🐾"
};
